---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>

name: glacier-os
description: This is my personal OS image with proprietary NVIDIA drivers.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # or latest

modules:
 
  # -----------------------------------------------
  #  NVIDIA's proprietary driver support
  # -----------------------------------------------
  
  - type: akmods
    base: main
    install: [] 
    nvidia-driver: nvidia

  - type: files
    files:
      - source: system/etc/environment
        destination: /etc/

  # -----------------------------------------------
  #  Kernel arguments for the GRUB file
  # -----------------------------------------------

  - type: kargs
    arch: x86_64
    kargs:
      - mitigations=off
      - rd.luks.options=discard,no-read-workqueue,no-write-workqueue

  # -----------------------------------------------
  #  Main repos and packages
  # -----------------------------------------------
  
  - type: dnf
    install:
      skip-unavailable: true
      packages:
        - steam-devices
        - android-tools
        - papirus-icon-theme
        - adw-gtk3-theme

    remove:
      auto-remove: true
      packages:
        - firefox
        - firefox-langpacks
        - gnome-tour

  # -----------------------------------------------
  #  3rd party repos and packages
  # -----------------------------------------------
  
  - type: dnf
    repos:
      cleanup: true
      copr:
        - atim/starship
        - abn/throttled
      keys:
        - https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key   # insync keys
      files:
        - insync.repo
    
    install:
      skip-unavailable: true
      install-weak-deps: true
      allow-erasing: true
      packages:
        - throttled
        - starship
        - tailscale
        - uld      
        - insync
        - insync-nautilus

    remove:
      auto-remove: true
      packages:
        - thermald
        
  - type: script
    scripts:
      - setup-autofirma.sh

  # -----------------------------------------------
  #  FLATPAKS
  # -----------------------------------------------
      
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        repo: 
          title: Flathub (system)
        install:
          # BASIC TOOLS
          - io.github.kolunmi.Bazaar
          - org.mozilla.firefox
          - it.mijorus.gearlever
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - page.tesk.Refine
          - com.ranfdev.DistroShelf
          - io.github.flattool.Warehouse
          - io.github.fabrialberio.pinapp
          - org.bleachbit.BleachBit
          
          # BACKUP
          - io.github.vikdevelop.SaveDesktop
          - org.gnome.World.PikaBackup
          
          # GNOME APPS
          - org.gnome.Calculator
          - org.gnome.Calendar
	  - org.gnome.Contacts
	  - org.gnome.FileRoller
          - org.gnome.Papers
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.Geary
          
          # THEMING
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
	  - dev.qwery.AddWater
          - io.github.Foldex.AdwSteamGtk
          
          # GAMING
          - com.valvesoftware.Steam
          - com.vysp3r.ProtonPlus
          - com.github.Matoking.protontricks
          - com.usebottles.bottles          
          - com.heroicgameslauncher.hgl
          - org.freedesktop.Platform.VAAPI.nvidia
          - org.freedesktop.Platform.VAAPI.Intel
          - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
          
          # OFFICE
          - org.onlyoffice.desktopeditors          
          - io.github.diegoivan.pdf_metadata_editor
          - com.github.jeromerobert.pdfarranger          
          - org.gnome.SimpleScan          
          - md.obsidian.Obsidian
          - be.alexandervanhee.gradia
          - com.github.flxzt.rnote
          
          # MULTIMEDIA
          - org.gnome.Showtime
          - com.spotify.Client
          - com.stremio.Stremio
          - com.github.wwmm.easyeffects
          - org.rncbc.qpwgraph
          - app.drey.EarTag
          - fm.reaper.Reaper
          
          # INTERNET & CONNECTVITY
          - de.haeckerfelix.Fragments
          - org.nickvision.tubeconverter
          - dev.deedles.Trayscale

  # -----------------------------------------------
  #  FILES & PARAMETERS
  # -----------------------------------------------
  
  - type: files
    files:
      # Starship related files
      - source: system/dev/starship-profile
        destination: /etc/profile.d/

      # Bootc instead of rpm-ostree updates  
      - source: system/common/bootc-service-override
        destination: /etc/systemd/system/bootc-fetch-apply-updates.service.d/
     
  #- type: justfiles
  
  # -----------------------------------------------
  #  SYSTEMD SERVICES
  # -----------------------------------------------
  
  - type: systemd
    system:
      enabled:
        - tailscaled.service
        - throttled.service
      disabled:
        - NetworkManager-wait-online.service

  # -----------------------------------------------
  #  GNOME EXTENSIONS
  # -----------------------------------------------

  - type: gnome-extensions
    install:
      - 3193  # Blur My Shell
      - 4481  # Forge
      - 517   # Caffeine
      - 615   # AppIndicator Support
      - 1319  # GSConnect
      - 3780  # ddterm
      - 4158  # Gnome 4x UI Improvements
      - 2236  # Night Theme Switcher
      - 355   # Status Area Horizontal Spacing
      - 4491  # Privacy Quick Settings
      - 4269  # Alphabetical App Grid
      - 5724  # Battery Health Charging
      - 7048  # Rounded Window Corners Reborn
      - 5105  # RebootToUEFI
      - 3956  # GNOME Fuzzy App Search
      - 8277  # Screen Brightness Governor
      - 7406  # Spotify Controls + Track Info
      - 7074  # GameMode Shell Extension
      - 4691  # PiP on top
      - 355   # Status Area Horizontal Spacing
 
  - type: gschema-overrides
    include:
      - zz1.settings.gschema.override
      #- zz2.extensions.gschema.override
      #- zz3.extension-settings.gschema.override

  - type: signing # Necessary for signing files
